### ISSUE TITLE
Failed to Convert

### ISSUE THREAD

**Issue by aknewhope** [yorikvanhavre/Draft-dxf-importer#3] opened 2014-07-17 23:18 UTC
This is what I get when trying to export from a step file to dwg or dxf. The file I am using is below. I had no problems before with FreeCAD 0.13 but it was the 32-bit version and the conversion was included with FreeCAD. I have not tried 32-bit version of FreeCAD 0.14 but I have uninstalled completely everything including all registry entries and user folders. This didn't help. 

System:
FreeCAD 0.14 3700 64-bit 
Windows 7 64-bit 6.1.7601 SP1(6.1.7601.17514)
Intel Core i7 second generation

File trying to be converted(worked before):
http://murrplastik.de/3dmodel/kdh/KDL_E_16_8.zip

Report View Output:
DXF libraries need to be updated. Downloading...
downloading https://raw.github.com/yorikvanhavre/Draft-dxf-importer/master/dxfColorMap.py ...
Download of dxf libraries failed. Please download them manually from
https://github.com/yorikvanhavre/Draft-dxf-importer
and place them in your macros folder
downloading https://raw.github.com/yorikvanhavre/Draft-dxf-importer/master/dxfImportObjects.py ...
Download of dxf libraries failed. Please download them manually from
https://github.com/yorikvanhavre/Draft-dxf-importer
and place them in your macros folder
downloading https://raw.github.com/yorikvanhavre/Draft-dxf-importer/master/dxfLibrary.py ...
Download of dxf libraries failed. Please download them manually from
https://github.com/yorikvanhavre/Draft-dxf-importer
and place them in your macros folder
downloading https://raw.github.com/yorikvanhavre/Draft-dxf-importer/master/dxfReader.py ...
Download of dxf libraries failed. Please download them manually from
https://github.com/yorikvanhavre/Draft-dxf-importer
and place them in your macros folder
Traceback (most recent call last):
  File "<string>", line 4, in <module>
  File "C:\Program Files\FreeCAD 0.14\Mod\Draft\importDXF.py", line 1808, in export
    dxf.saveas(filename)
  File "C:/Users/jreese.CALMATION/AppData/Roaming/FreeCAD\dxfLibrary.py", line 904, in saveas
    else: self.export()
  File "C:/Users/jreese.CALMATION/AppData/Roaming/FreeCAD\dxfLibrary.py", line 922, in export
    self._write_section(outfile,'blocks',self.blocks)
  File "C:/Users/jreese.CALMATION/AppData/Roaming/FreeCAD\dxfLibrary.py", line 896, in _write_section
    file.write(str(x))
  File "C:/Users/jreese.CALMATION/AppData/Roaming/FreeCAD\dxfLibrary.py", line 619, in __str__
    e=''.join([str(x)for x in self.entities])
  File "C:/Users/jreese.CALMATION/AppData/Roaming/FreeCAD\dxfLibrary.py", line 399, in __str__
    result+='%s\n' %_point(point[0])
  File "C:/Users/jreese.CALMATION/AppData/Roaming/FreeCAD\dxfLibrary.py", line 106, in _point
    return '\n'.join([' %s\n%s'%((i+1)*10+index,float(x[i])) for i in range(len(x))])
<type 'exceptions.TypeError'>: object of type 'float' has no len()
Stack Trace: Traceback (most recent call last):
  File "<string>", line 4, in <module>
  File "C:\Program Files\FreeCAD 0.14\Mod\Draft\importDXF.py", line 1808, in export
    dxf.saveas(filename)
  File "C:/Users/jreese.CALMATION/AppData/Roaming/FreeCAD\dxfLibrary.py", line 904, in saveas
    else: self.export()
  File "C:/Users/jreese.CALMATION/AppData/Roaming/FreeCAD\dxfLibrary.py", line 922, in export
    self._write_section(outfile,'blocks',self.blocks)
  File "C:/Users/jreese.CALMATION/AppData/Roaming/FreeCAD\dxfLibrary.py", line 896, in _write_section
    file.write(str(x))
  File "C:/Users/jreese.CALMATION/AppData/Roaming/FreeCAD\dxfLibrary.py", line 619, in __str__
    e=''.join([str(x)for x in self.entities])
  File "C:/Users/jreese.CALMATION/AppData/Roaming/FreeCAD\dxfLibrary.py", line 399, in __str__
    result+='%s\n' %_point(point[0])
  File "C:/Users/jreese.CALMATION/AppData/Roaming/FreeCAD\dxfLibrary.py", line 106, in _point
    return '\n'.join([' %s\n%s'%((i+1)*10+index,float(x[i])) for i in range(len(x))])

**Comment by yorikvanhavre** [comment] 2015-09-12 17:20
Sorry, actually I'm just discovering these issues now...
Iḿ closing this report as it is probably fixed in0.16 (the file is not available anymore, I can't test), please reopen if the problem is still there.

**Closed by yorikvanhavre** 2015-09-12 17:20 UTC

**Comment by satheesh7** [comment] 2016-05-23 05:39
Hi,
I am using freecad 0.16 in windows 7. while i am trying to export a file in dxf, the following error is coming.
![capture](https://cloud.githubusercontent.com/assets/19525689/15461230/d5f22e8e-20d6-11e6-9c8e-35f7a70c3960.PNG)

**Comment by yorikvanhavre** [comment] 2016-05-23 14:50
@satheesh7 did you do all the steps that are mentioned in the given page?
Also it's best to discuss this on http://forum.freecadweb.org you will get faster and better help...
